stages:
  - test
  - build
  - deploy

test:
  image: library/golang:1.21-alpine
  stage: test
  script:
    - go vet .
    - go build -o jinya-ip-locator

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}/ARCH:1.0.${CI_PIPELINE_IID}"
      --destination "${CI_REGISTRY_IMAGE}/ARCH:latest"
      --destination "jinyacms/jinya-ip-locator:1.0.${CI_PIPELINE_IID}"
      --destination "jinyacms/jinya-ip-locator:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - runner-${ARCH}

merge-manifests:
  stage: deploy
  needs:
    - job: docker-build
      artifacts: false
  image:
    name: mplatform/manifest-tool:alpine
    entrypoint: [""]
  script:
    - >-
      manifest-tool
      --username=${CI_REGISTRY_USER}
      --password=${CI_REGISTRY_PASSWORD}
      push from-args
      --platforms linux/amd64,linux/arm64
      --template ${CI_REGISTRY_IMAGE}/ARCH:${TAG}
      --target ${CI_REGISTRY_IMAGE}:${TAG}
  parallel:
    matrix:
      - TAG: latest
      - TAG: 1.0.${CI_COMMIT_BRANCH}
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"

binary-build-linux:
  image: library/golang:1.21-alpine
  stage: build
  script:
    - go build -o jinya-ip-locator
  artifacts:
    paths:
      - jinya-ip-locator
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"

binary-build-windows:
  image: library/golang:1.21-alpine
  stage: build
  variables:
    GOOS: windows 
  script:
    - go build -o jinya-ip-locator.exe
  artifacts:
    paths:
      - jinya-ip-locator.exe
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"