stages:
  - test
  - build
  - deploy

test:
  image: library/golang:1.24-alpine
  stage: test
  script:
    - go vet .
    - go build -o jinya-ip-locator

docker-build:
  stage: deploy
  image: registry.ulbricht.casa/docker-images/buildah:latest
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKERHUB_PASSWORD" | buildah login -u "$DOCKERHUB_USER" --password-stdin docker.io
  variables:
    IMG: $CI_REGISTRY_IMAGE/$ARCH:1.0.$CI_PIPELINE_IID
  script:
    - buildah build --platform=linux/$ARCH -t $IMG .
    - buildah push $IMG
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"
  parallel:
    matrix:
      - ARCH: amd64
      - ARCH: arm64
  tags:
    - performance

merge-manifests:
  stage: deploy
  needs:
    - job: docker-build
      artifacts: false
  image: registry.ulbricht.casa/docker-images/buildah:latest
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY
    - echo "$DOCKERHUB_PASSWORD" | buildah login -u "$DOCKERHUB_USER" --password-stdin docker.io
  script:
    - buildah manifest create $FQ_IMAGE_NAME
    - buildah manifest add $FQ_IMAGE_NAME docker://$CI_REGISTRY_IMAGE/amd64:1.0.$CI_PIPELINE_IID
    - buildah manifest add $FQ_IMAGE_NAME docker://$CI_REGISTRY_IMAGE/arm64:1.0.$CI_PIPELINE_IID
    - buildah manifest push --all $FQ_IMAGE_NAME
  parallel:
    matrix:
      - FQ_IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
      - FQ_IMAGE_NAME: $CI_REGISTRY_IMAGE:1.0.$CI_PIPELINE_IID
      - FQ_IMAGE_NAME: docker.io/jinyacms/jinya-ip-locator:latest
      - FQ_IMAGE_NAME: docker.io/jinyacms/jinya-ip-locator:1.0.$CI_PIPELINE_IID
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"