stages:
  - test
  - build
  - deploy

test:
  image: harbor.ulbricht.casa/proxy/library/golang:1.21-alpine
  stage: test
  script:
    - go vet .
    - go build -o jinya-ip-locator

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo $KANIKO_DOCKERHUB_AND_HARBOR > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "harbor.ulbricht.casa/jinya/jinya-ip-locator:1.0.${CI_PIPELINE_IID}"
      --destination "harbor.ulbricht.casa/jinya/jinya-ip-locator:latest"
      --destination "jinyacms/jinya-ip-locator:1.0.${CI_PIPELINE_IID}"
      --destination "jinyacms/jinya-ip-locator:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"
      exists:
        - Dockerfile

binary-build-linux:
  image: harbor.ulbricht.casa/proxy/library/golang:1.21-alpine
  stage: build
  script:
    - go build -o jinya-ip-locator
  artifacts:
    paths:
      - jinya-ip-locator
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"

binary-build-windows:
  image: harbor.ulbricht.casa/proxy/library/golang:1.21-alpine
  stage: build
  variables:
    GOOS: windows 
  script:
    - go build -o jinya-ip-locator.exe
  artifacts:
    paths:
      - jinya-ip-locator.exe
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"