stages:
  - test
  - build
  - deploy

test:
  image: library/golang:1.21-alpine
  stage: test
  script:
    - go vet .
    - go build -o jinya-ip-locator

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    pull_policy: always
    entrypoint: [""]
  before_script:
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"},\"https://index.docker.io/v1/\":{\"auth\":\"$DOCKER_TOKEN\"}}}" > /kaniko/.docker/config.json
  script:
    - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${CI_REGISTRY_IMAGE}:1.0.${CI_PIPELINE_IID}"
      --destination "${CI_REGISTRY_IMAGE}:latest"
      --destination "jinyacms/jinya-ip-locator:1.0.${CI_PIPELINE_IID}"
      --destination "jinyacms/jinya-ip-locator:latest"
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"
      exists:
        - Dockerfile

binary-build-linux:
  image: library/golang:1.21-alpine
  stage: build
  script:
    - go build -o jinya-ip-locator
  artifacts:
    paths:
      - jinya-ip-locator
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"

binary-build-windows:
  image: library/golang:1.21-alpine
  stage: build
  variables:
    GOOS: windows 
  script:
    - go build -o jinya-ip-locator.exe
  artifacts:
    paths:
      - jinya-ip-locator.exe
  rules:
    - if: $CI_COMMIT_BRANCH == "v1"